package migrations

import "github.com/rubenv/sql-migrate"

func ConvertDatetimeToTimestamp() *migrate.Migration {
	convertDateTimeToTimestamp := migrate.Migration{
		Id: "6",
		Up: []string{`
			ALTER TABLE gocms_emails
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_groups
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_groups_to_permissions
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_permissions
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_plugins
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_runtime
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_secure_codes
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
			`,`
			ALTER TABLE gocms_settings
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_users
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_users_to_groups
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,`
			ALTER TABLE gocms_users_to_permissions
			CHANGE COLUMN created created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			CHANGE COLUMN lastModified lastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
			`,
		},
		Down: []string{
		},
	}

	return &convertDateTimeToTimestamp
}
