package consts

const USER_KEY_FOR_GIN_CONTEXT = "user"
const GOCMS_HEADER_USER_CONTEXT_KEY = "X-GOCMS-USER-CONTEXT"
const GOCMS_HEADER_TIMEZONE_KEY = "X-GOCMS-TIMEZONE"
const GOCMS_HEADER_MICROSERVICE_SECRET = "X-GOCMS-MICROSERVICE-SECRET"

const GOCMS_MIDDLEWARE_URL_SEGMENT = "middleware"
